bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: nova_carter
    navigators: [navigate_to_pose, navigate_through_poses]
    navigate_to_pose:
      plugin: nav2_bt_navigator::NavigateToPoseNavigator
    navigate_through_poses:
      plugin: nav2_bt_navigator::NavigateThroughPosesNavigator

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    progress_checker_plugins: [progress_checker]
    goal_checker_plugins: [goal_checker]
    controller_plugins: [FollowPath]
    progress_checker:
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.25
      movement_time_allowance: 15.0
    goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true
    FollowPath:
      plugin: nav2_mppi_controller::MPPIController
      motion_model: DiffDrive
      time_steps: 56
      model_dt: 0.05
      batch_size: 2000
      vx_max: 0.80
      vx_min: -0.40
      wz_max: 1.8
      iteration_count: 1
      prune_distance: 1.7
      transform_tolerance: 0.3
      visualize: false
      regenerate_noises: true
      critics: [ConstraintCritic, ObstaclesCritic, GoalCritic, GoalAngleCritic, PathAlignCritic, PathFollowCritic, PreferForwardCritic]
      ObstaclesCritic:
        enabled: true

collision_monitor:
  ros__parameters:
    use_sim_time: true
    base_frame_id: nova_carter
    odom_frame_id: map
    cmd_vel_in_topic: cmd_vel_smoothed
    cmd_vel_out_topic: cmd_vel
    observation_sources: [pointcloud]
    pointcloud:
      type: pointcloud
      topic: /front_3d_lidar/lidar_points
      min_height: 0.10
      max_height: 1.50
      enabled: true
    polygons: [SafeZone]
    SafeZone:
      type: circle
      radius: 0.35
      action_type: stop
      min_points: 4
      enabled: true

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 1.0
    planner_plugins: [GridBased]
    GridBased:
      plugin: nav2_smac_planner::SmacPlanner2D
      tolerance: 0.25
      allow_unknown: true
      max_iterations: 100000
      max_planning_time: 2.0

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: [simple_smoother]
    simple_smoother:
      plugin: nav2_smoother::SimpleSmoother
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

behavior_server:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: nova_carter
    behavior_plugins: [spin, backup, drive_on_heading, assisted_teleop, wait]
    spin:
      plugin: nav2_behaviors::Spin
    backup:
      plugin: nav2_behaviors::BackUp
    drive_on_heading:
      plugin: nav2_behaviors::DriveOnHeading
    assisted_teleop:
      plugin: nav2_behaviors::AssistedTeleop
    wait:
      plugin: nav2_behaviors::Wait

docking_server:
  ros__parameters:
    use_sim_time: true
    base_frame: nova_carter
    fixed_frame: map
    dock_plugins: [sim_dock]
    sim_dock:
      plugin: opennav_docking::SimpleChargingDock
      staging_x_offset: -0.7
    docks: [home_dock]
    home_dock:
      type: sim_dock
      frame: map
      pose: [0.0, 0.0, 0.0]

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: wait_at_waypoint
    wait_at_waypoint:
      plugin: nav2_waypoint_follower::WaitAtWaypoint
      enabled: true
      waypoint_pause_duration: 0

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: OPEN_LOOP
    max_velocity: [0.80, 0.0, 1.8]
    min_velocity: [-0.40, 0.0, -1.8]
    max_accel: [2.0, 0.0, 3.0]
    max_decel: [-2.0, 0.0, -3.0]
    odom_duration: 0.1
    velocity_timeout: 1.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: nova_carter
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05
      transform_tolerance: 0.3
      footprint: "[[0.14, 0.25], [0.14, -0.25], [-0.607, -0.25], [-0.607, 0.25]]"
      plugins: [nvblox_layer, inflation_layer]
      nvblox_layer:
        plugin: nvblox::nav2::NvbloxCostmapLayer
        enabled: true
        nav2_costmap_global_frame: map
        nvblox_map_slice_topic: /nvblox_node/static_map_slice
        convert_to_binary_costmap: true
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        inflation_radius: 0.70
        cost_scaling_factor: 10.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: nova_carter
      width: 60
      height: 60
      origin_x: -30.0
      origin_y: -30.0
      resolution: 0.05
      track_unknown_space: false
      transform_tolerance: 0.3
      footprint: "[[0.14, 0.25], [0.14, -0.25], [-0.607, -0.25], [-0.607, 0.25]]"
      plugins: [nvblox_layer, inflation_layer]
      nvblox_layer:
        plugin: nvblox::nav2::NvbloxCostmapLayer
        enabled: true
        nav2_costmap_global_frame: map
        nvblox_map_slice_topic: /nvblox_node/static_map_slice
        convert_to_binary_costmap: true
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        inflation_radius: 0.70
        cost_scaling_factor: 10.0

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: [controller_server, smoother_server, planner_server, behavior_server, bt_navigator, waypoint_follower, velocity_smoother]
